pipeline {
  agent any
  stages {
    stage('Preparation') {
      steps {
        sh '''
        docker version
        docker info
        docker-compose version
        curl --version
        '''
      }
    }

    stage('Deploy Lomba Backend') {
      steps {
        sh 'docker-compose -f ./docker-compose.yml -p "lombalocal" up --build -d'
        }
      }

    }
  }