pipeline {
  agent any
  stages {
    stage('Preparation') {
      steps {
        sh '''
        docker version
        docker info
        docker-compose version
        curl --version
        chmod 777 /var/run/docker.sock
        '''
      }
    }

    stage('Deploy Lomba Front and Back') {
      steps {
        sh 'docker-compose -f ./run_frontback_local/docker-compose.yml -p "lombalocalall" up --build --force-recreate -d'
        }
      }

    }
  }